accounts/urls.py
from django.conf import settings
from django.conf.urls import url
from django.conf.urls.static import static
from django.contrib.auth.views import login, logout
from . import views

urlpatterns = [
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, {'next_page': 'index'}, name='logout'),
    #url(r'^signup/$', views.sign_up, name="signup"),
    url(r'^resume/$', views.resume, name="resume"),
]

hackerthon/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from idea import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^idea/', include('idea.urls', namespace='idea')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idea/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new/$', views.idea_new, name='idea_new'),
    url(r'^$', views.idea_list, name="idea_list" ),
    url(r'^(?P<pk>\d+)/$', views.idea_detail, name='idea_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.idea_edit, name='idea_edit'),
    url(r'^(?P<pk>\d+)/del/$', views.idea_del, name='idea_del'),
    url(r'^(?P<idea_pk>\d+)/comment/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^(?P<idea_pk>\d+)/comment/(?P<pk>\d+)/del/$', views.comment_del, name='comment_del'),
    #Sample
    url(r'^location/$', views.location, name="location")
]

hackerthon/templates/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:type" content="website">
<meta property="og:title" content="P.rogreSV">
<meta property="og:url" content="p.rogresv.com">
<meta property="og:description" content="P.rogreSV 해커톤">
<meta property="og:image" content="{% static 'img/home-bg.jpg' %}">
<title>P.rogreSV</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.css' %}" rel="stylesheet" type="text/css">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css"> -->

    <!-- Theme CSS -->
    <link href="{% static 'css/clean-blog.min.css'%}" rel="stylesheet" type="text/css">
    <!-- idea_list CSS -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css" rel="stylesheet" type="text/css">
    <!-- comment CSS -->
    <link href="{% static 'css/comment.css'%}" rel="stylesheet" type="text/css">

    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/typed.js' %}" type="text/javascript"></script>

    <!-- message CSS -->
    <link href="{% static 'css/animate.css' %}" rel = "stylesheet" type="text/css">

</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header page-scroll">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">P.rogreSV</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right">
                <li>
                    <a href="{% url 'index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'idea:idea_list'%}">Idea</a>
                </li>
                <li>
                    <a href="{% url 'idea:location' %}">Location</a>
                </li>
                {%if not user.is_authenticated %}
                <li>
                    <a href="{% url 'accounts:login' %}">Login</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'accounts:logout'%}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
{% block content %}
{% endblock %}
<!-- Footer -->
<footer>
    <div class="col-sm-10 col-sm-offset-2">
        <div class="row col-sm-10">
            <hr>
            <span style="font-family : sans-serif;">
            주최 : 서울대학교 산학협력단, 서울대학교 기술지주회사, 서울대학교 벤처경영기업가센터
            <hr>
            주관 : 교육부, 중소기업청, 창업진흥원
            <hr>
            후원 : 스윗트래커, 서울대학교 해동 아이디어팩토리
            <hr>
            Developed by P.rogramming [공현택, 김범준, 안주은]  Powered by Django
            </span>
            <br><br><br>
        </div>
    </div>
</footer>

    <link href="{% static 'css/main.css'%}" rel="stylesheet"/>
    <style>
        /* code for animated blinking cursor */
        .typed-cursor{
            opacity: 1;
            font-weight: 100;
            -webkit-animation: blink 0.7s infinite;
            -moz-animation: blink 0.7s infinite;
            -ms-animation: blink 0.7s infinite;
            -o-animation: blink 0.7s infinite;
            animation: blink 0.7s infinite;
        }
        @-keyframes blink{
            0% { opacity:1; }
            50% { opacity:0; }
            100% { opacity:1; }
        }
        @-webkit-keyframes blink{
            0% { opacity:1; }
            50% { opacity:0; }
            100% { opacity:1; }
        }
        @-moz-keyframes blink{
            0% { opacity:1; }
            50% { opacity:0; }
            100% { opacity:1; }
        }
        @-ms-keyframes blink{
            0% { opacity:1; }
            50% { opacity:0; }
            100% { opacity:1; }
        }
        @-o-keyframes blink{
            0% { opacity:1; }
            50% { opacity:0; }
            100% { opacity:1; }
        }
    </style>

    <!-- wow.js -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/wow/1.1.2/wow.min.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %} "></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js'%}"></script>

    {% block script %}
    {% endblock %}
</body>
</html>

hackerthon/templates/form.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta property="og:type" content="website">
<meta property="og:title" content="P.rogreSV">
<meta property="og:url" content="p.rogresv.com">
<meta property="og:description" content="P.rogreSV 해커톤">
<meta property="og:image" content="{% static 'img/home-bg.jpg' %}">
<title>P.rogreSV</title>
    <!-- Bootstrap Core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css"> -->

    <!-- Theme CSS -->
    <link href="{% static 'css/clean-blog.min.css'%}" rel="stylesheet">

    <!-- Message CSS -->
    <link href="{% static 'css/animate.css' %}" rel = "stylesheet" type="text/css">

</head>
<body>
<!-- Navigation -->
<nav class="navbar navbar-default navbar-custom navbar-fixed-top" style="background : black;">
    <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header " style="font-color : black;">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                <span class="sr-only">Toggle navigation</span>
                Menu <i class="fa fa-bars"></i>
            </button>
            <a class="navbar-brand" href="{% url 'index' %}">P.rogreSV</a>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav navbar-right" style="font-color : black;">
                <li>
                    <a href="{% url 'index' %}">Home</a>
                </li>
                <li>
                    <a href="{% url 'idea:idea_list'%}">Idea</a>
                </li>
                <li>
                    <a href="{% url 'idea:location' %}">Contact</a>
                </li>
                {%if not user.is_authenticated %}
                <li>
                    <a href="{% url 'accounts:login' %}">Login</a>
                </li>
                {% else %}
                <li>
                    <a href="{% url 'accounts:logout'%}">Logout</a>
                </li>
                {% endif %}
            </ul>
        </div>
        <!-- /.navbar-collapse -->
    </div>
    <!-- /.container -->
</nav>
{% block content %}

{% endblock %}
<!-- Footer -->
<footer>
    <div class="col-sm-10 col-sm-offset-2">
        <div class="row col-sm-10">
            <hr>
            <span style="font-family : sans-serif;">
            주최 : 서울대학교 산학협력단, 서울대학교 기술지주회사, 서울대학교 벤처경영기업가센터
            <hr>
            주관 : 교육부, 중소기업청, 창업진흥원
            <hr>
            후원 : 스윗트래커, 서울대학교 해동 아이디어팩토리
            <hr>
            Developed by P.rogramming [공현택, 김범준, 안주은]  Powered by Django
            </span>
            <br><br><br>
        </div>
    </div>
</footer>


    <!-- jQuery -->
    <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %} "></script>

    <!-- Contact Form JavaScript -->
    <script src="{% static 'js/jqBootstrapValidation.js' %}"></script>
    <script src="{% static 'js/contact_me.js' %}"></script>

    <!-- Theme JavaScript -->
    <script src="{% static 'js/clean-blog.min.js'%}"></script>
    {% block script %}
    {% endblock %}
</body>
</html>