hackerthon/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin

from idea import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^idea/', include('idea.urls', namespace='idea')),
    url(r'^accounts/', include('accounts.urls', namespace='accounts')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'', include('social.apps.django_app.urls', namespace='social')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

idea/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^new/$', views.idea_new, name='idea_new'),
    url(r'^$', views.idea_list, name="idea_list" ),
    url(r'^(?P<pk>\d+)/$', views.idea_detail, name='idea_detail'),
    url(r'^(?P<pk>\d+)/edit/$', views.idea_edit, name='idea_edit'),
    url(r'^(?P<pk>\d+)/del/$', views.idea_del, name='idea_del'),
    url(r'^(?P<idea_pk>\d+)/comment/(?P<pk>\d+)/edit/$', views.comment_edit, name='comment_edit'),
    url(r'^(?P<idea_pk>\d+)/comment/(?P<pk>\d+)/del/$', views.comment_del, name='comment_del'),
    #Sample
    url(r'^location/$', views.location, name="location")
]

idea/models.py
from django.conf import settings
from django.db import models

class Idea(models.Model):
    title = models.CharField(max_length=40)
    contents = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    recommend = models.PositiveSmallIntegerField(default=0)
    image = models.ImageField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    def __str__(cls):
        return cls.title


class Comment(models.Model):
    idea = models.ForeignKey(Idea)
    contents = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(cls):
        return cls.author

class Vote(models.Model):
    vote_user = models.ForeignKey(settings.AUTH_USER_MODEL)
    vote_idea = models.ForeignKey(Idea)

idea/forms.py
from django import forms
from django.forms.widgets import FileInput
from .models import Idea, Comment, Vote

class IdeaForm(forms.ModelForm):
    class Meta:
        model = Idea
        fields = ['title', 'contents', 'image', ]
        labels = {
            'title': '제목',
            'contents': '내용',
            'image': '이미지',
        }
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': '제목'}),
            'contents': forms.Textarea(attrs={'placeholder': '컨텐츠'}),
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['contents', ]
        widgets = {
            'contents': forms.Textarea(attrs={'placeholder': '내용 입력', 'rows': 2}),
        }

idea/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Idea, Comment, Vote
from .forms import IdeaForm, CommentForm
from hackerthon.decorators import user_wrote_this, get_resume
from django.contrib.auth.models import User
from allauth.socialaccount.models import SocialAccount
from django.utils import timezone
from datetime import timedelta
from django.db.models import Count
from accounts.models import Resume

def index(request):
    social_accounts_kakao = SocialAccount.objects.filter(provider="kakao")
    kakaos = {}
    resume_list = Resume.objects.all()
    """
    for resume in resume_list:
        for kakao in social_accounts_kakao:
            if int(resume.user.username[6:]) == kakao.extra_data['id']:
                kakaos[kakao.extra_data['id']] = resume.name + ',' + kakao.extra_data['properties']['profile_image'] + ',' + "resume" + ',' +resume.group + ',' + resume.position
    for kakao in social_accounts_kakao:
        if not kakao.extra_data['id'] in kakaos.keys():
            kakaos[kakao.extra_data['id']] = kakao.extra_data['name'] +','+ kakao.extra_data['properties']['profile_image'] + ',' +'kakao'
    """
    for kakao in social_accounts_kakao:
        try:
            resume = Resume.objects.get(user=kakao.user)
        except Resume.DoesNotExist:
            kakaos[kakao.extra_data['id']] = kakao.extra_data['name'] + ',' + kakao.extra_data['properties']['profile_image'] + ',' + 'kakao'
        else:
            kakaos[kakao.extra_data['id']] = resume.name + ',' + kakao.extra_data['properties']['profile_image'] + ',' + "resume" + ',' + resume.group + ',' + resume.position
    return render(request, 'idea/index.html',{
        'kakaos':kakaos,
        })

def idea_list(request):
    idea_list = Idea.objects.all().annotate(vote_count = Count('vote')).order_by('-vote_count')
    return render(request, 'idea/idea_list.html', {'idea_list': idea_list})

def convert_timedelta(duration):
    days, seconds = duration.days, duration.seconds
    hours = seconds // 3600
    minutes = (seconds % 3600) // 60
    seconds = (seconds % 60)
    return days, hours, minutes, seconds

def generate_elapsed_time(duration):
    day, hour, mins, sec = convert_timedelta(duration)
    if day >= 365:
        elapsed_time = str(day // 365) + ' year ago'
    elif day >= 30:
        elapsed_time = str(day // 30) + ' month ago'
    elif day >= 7:
        elapsed_time = str(day // 7) + ' week ago'
    elif day > 0:
        elapsed_time = str(day) + ' day ago'
    elif hour > 0:
        elapsed_time = str(hour) + ' hour ago'
    elif mins > 0:
        elapsed_time = str(mins) + ' minute ago'
    elif sec > 0:
        elapsed_time = str(sec) + ' seconds ago'
    else:
        elapsed_time = 'now'
    return elapsed_time


@login_required
@get_resume()
def idea_detail(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    request_post = request.POST.dict()
    if request.method == "POST" and request.is_ajax() and request_post['formtype'] == 'comment-add':
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.idea = idea
            comment.author = request.user
            comment.save()
            local_now = timezone.localtime(timezone.now())
            comments = Comment.objects.filter(idea = idea)
            for comment in comments:
                comment.elapsed_time = generate_elapsed_time(local_now - comment.updated_at)
            context = {
                'idea' : idea,
                'comments' : comments,
            }
            return render(request, 'idea/idea_comment.html', context)
    elif request.method == "POST" and request.is_ajax() and request_post['formtype'] == 'comment-edit':
        # comment_edit(request, pk, str(request_post['comment']))
        comment = get_object_or_404(Comment, pk=request_post['comment'])
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save()
            local_now = timezone.localtime(timezone.now())
            comments = Comment.objects.filter(idea = idea)
            for comment in comments:
                comment.elapsed_time = generate_elapsed_time(local_now - comment.updated_at)
            context = {
                'idea' : idea,
                'comments' : comments,
            }
            return render(request, 'idea/idea_comment.html', context)
    elif request.method == "POST":
        if Vote.objects.filter(vote_user = request.user).count()<4 and not Vote.objects.filter(vote_user=request.user, vote_idea=idea).exists():
            #메세지 넣기
            Vote.objects.create(vote_user=request.user, vote_idea = idea)
            return redirect('idea:idea_detail', pk=idea.pk)
        elif Vote.objects.filter(vote_user=request.user, vote_idea=idea).exists():
            Vote.objects.filter(vote_user=request.user, vote_idea=idea).delete()
            return redirect('idea:idea_detail', pk=idea.pk)
        else:
            #실패했다는 메세지 넣어야함
            return redirect('idea:idea_detail', pk=idea.pk)
    else:
        social_accounts = SocialAccount.objects.all()
        form = CommentForm()
        local_now = timezone.localtime(timezone.now())
        comments = Comment.objects.filter(idea = idea)
        vote = Vote.objects.filter(vote_user=request.user, vote_idea=idea).exists()
        for comment in comments:
            comment.elapsed_time = generate_elapsed_time(local_now - comment.updated_at)
        return render(request, 'idea/idea_detail.html', {
            'idea' : idea,
            'comments' : comments,
            'form' : form,
            'vote': vote,
            })


@login_required
@get_resume()
def idea_new(request):
    if request.method == "POST":
        form = IdeaForm(request.POST, request.FILES)
        if form.is_valid():
            idea = form.save(commit=False)
            idea.author = request.user
            idea.save()
            return redirect('idea:idea_detail', pk=idea.pk)
    else:
        form = IdeaForm()
    return render(request, 'idea/idea_form.html', {
        'form' : form,
        })


@login_required
@get_resume()
@user_wrote_this(Idea)
def idea_edit(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    if request.method == "POST":
        form = IdeaForm(request.POST, request.FILES, instance=idea)

        if form.is_valid():
            idea = form.save()
            return redirect('idea:idea_detail', pk=idea.pk)
    else:
        form = IdeaForm(instance = idea)
    return render(request, 'idea/idea_form.html', {
        'form' : form,
        })


@login_required
@get_resume()
@user_wrote_this(Idea)
def idea_del(request, pk):
    idea = get_object_or_404(Idea, pk=pk)
    idea.delete()
    return redirect('idea:idea_list')


@login_required
@get_resume()
@user_wrote_this(Comment)
def comment_edit(request, idea_pk, pk):
    idea = get_object_or_404(Idea, pk=idea_pk)
    comment = get_object_or_404(Comment, pk=pk)
    if request.method == "POST":
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save()
            local_now = timezone.localtime(timezone.now())
            comments = Comment.objects.filter(idea = idea)
            for comment in comments:
                comment.elapsed_time = generate_elapsed_time(local_now - comment.updated_at)
            context = {
                'idea' : idea,
                'comments' : comments,
            }
            return render(request, 'idea/idea_comment.html', context)
            # return redirect('idea:idea_detail', pk=idea_pk)
    # else:
    #     form = CommentForm(instance=comment)
    # return render(request, 'idea/comment_form.html', {
    #     'form' : form,
    #     })


@login_required
@get_resume()
@user_wrote_this(Comment)
def comment_del(request, idea_pk, pk):
    idea = get_object_or_404(Idea, pk=idea_pk)
    comment = get_object_or_404(Comment, pk=pk)
    comment.delete()
    return redirect('idea:idea_detail', idea_pk)

"""
def users(request):
    social_accounts_facebook = SocialAccount.objects.filter(provider = "facebook")
    social_accounts_kakao = SocialAccount.objects.filter(provider="kakao")
    kakaos = {}
    facebooks = {}
    for kakao in social_accounts_kakao:
        kakaos[kakao.extra_data['id']] = kakao.extra_data['name'] +','+ kakao.extra_data['properties']['profile_image']
    for facebook in social_accounts_facebook:
        facebooks[facebook.extra_data['id']] = facebook.extra_data['name']

    return render(request, "idea/users.html", {'kakaos':kakaos,'facebooks': facebooks})
"""
def location(request):
    return render(request, "idea/location.html")

idea/templates/idea/comment_form.html
{#
쓰지 않는 템플릿
{% extends 'base.html' %}
{% load bootstrap3 %}

{% block content %}
<br><br><br>
    <div class="container">
        <div class="col-md -9">
            <form action="" enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {%bootstrap_field form.contents%}
                <button type="submit" class="btn btn-primary">댓글 달기</button>
            </form>
        </div>
    </div>
</form>
{% endblock %}
 #}

idea/templates/idea/idea_comment.html
{%load staticfiles%}
{# 댓글 달때 ajax 처리 후 로딩하는 부분 #}
    {% if comments %}
        <section class="comment-list">
            {% for comment in comments %}
                <article class="row">
                    <div class="col-sm-2 hidden-xs">
                        {# ---프로필 사진이 들어갈 곳--- #}
                        <figure class="thumbnail user-photo">
                            {% if comment.author.socialaccount_set.all %}
                                {%for account in comment.author.socialaccount_set.all%}
                                    {% if account.extra_data.properties.profile_image %}
                                        <img src = {{account.extra_data.properties.profile_image}}>
                                    {% else %}
                                        <img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                                    {%endif%}
                                {% endfor %}
                            {% else %}
                                <img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" >
                            {%endif%}
                        </figure>
                    </div>
                    <div class="col-sm-9">
                        <div class="panel panel-default arrow left">
                            <div class="panel-body no-padding">
                                <header class="text-left">
                                    <div class="comment-user">
                                    {%if comment.author == user %}
                                    <div class="dropdown btn-group pull-right">
                                        <i class="fa fa-bars" aria-hidden="true" data-toggle="dropdown"></i>
                                        <ul class="dropdown-menu" style="min-width: 30px">
                                        <li><a href="javascript:void(0)" class="a_comment_edit">수정</a></li>
                                        <li><a href="{% url 'idea:comment_del' idea.pk comment.pk %}">삭제</a></li>
                                        </ul>
                                    </div>
                                    {% endif %}
                                    <i class="fa fa-user"></i>
                                        <strong>
                                        {% if comment.author.socialaccount_set.all %}
                                            {%for account in comment.author.socialaccount_set.all%}
                                                {% if account.provider == "facebook" %}
                                                    {{comment.author.last_name}}{{comment.author.first_name}}
                                                {% elif account.provider == "kakao" %}
                                                    {{comment.author.first_name}}
                                                {%endif%}
                                            {% endfor %}
                                        {% else %}
                                            {{comment.author}}
                                        {% endif %}
                                        </strong>
                                    </div>
                                    <time class="comment-date small text-muted">
                                        <i class="fa fa-clock-o"></i>
                                        {{comment.elapsed_time}}
                                        {% if comment.created_at|date:'YmdHms' != comment.updated_at|date:'YmdHms' %}
                                        (수정됨)
                                        {% endif %}
                                    </time>
                                </header>
                                {# <form action="" method="POST" enctype="multipart/form-data"> #}
                                    <input type="hidden" class="comment-pk" value="{{comment.pk}}">
                                    <div class="comment-post">
                                        <span class="comment-content">{{comment.contents}}</span>
                                    </div>
                                    <div class="comment-post-buttons" style="display:none">
                                        <button class="btn btn-primary btn-xs edit-submit">확인</button> <button class="btn btn-danger btn-xs edit-cancel">취소</button>
                                    </div>
                                {# </form> #}
                            </div>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </section>
    {% else %}
        <div class="row col-xs-12">
            댓글없음
        </div>
    {% endif %}

idea/templates/idea/idea_detail.html
{% extends 'base.html' %}
{% load bootstrap3 %}
{% load staticfiles %}
{% block content %}
{% load socialaccount account %}
{% load idea_extras %}
{% csrf_token %}
    <!-- Page Header -->
    <!-- Set your background image for this header on the line below. -->
    <header class="intro-header" style="background-image: url('{% static 'img/idea.jpg' %}')">
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <div class="page-heading idea">
                        <h1>Idea</h1>
                        <hr class="small">
                    </div>
                </div>
            </div>
        </div>
    </header>

    <div class="container col-md-11 col-md-offset-1">

        {# 글 내용 부분 #}
        <div class="row col-sm-11">
            <h1>
            <span>{{idea.title}}</span>
            {% if idea.author == user %}
            </h1>
            <h2>
            <span class="dropdown btn-group pull-right">
                <img src="{% static 'img/edit.png' %}" style="width: 40px;" id="edit">
                <img src="{% static 'img/delete.png' %}" style="width: 40px;" id="delete">
            </span>
            </h2>
            {% endif %}
            <p class="lead">
                by {{idea.author.resume.name}}
            </p>
            <hr>
            <p class = "lead">
                <i class="fa fa-clock-o"> Posted on {{idea.created_at|date:'Y-m-d H:i'}}</i><br>
                <i class="fa fa-refresh"> Last updated on {{idea.updated_at|date:'Y-m-d H:i'}}</i>
            </p>
            <hr>
            <img src="{{idea.image.url}}" class="img-responsive center-block" width="80%">
            <hr>
            <p class="lead">{{idea.contents|linebreaks}}</p>
            <hr>
            <form action="" method="POST" enctype="multipart/form-data" class="text-center">
                {% csrf_token %}
                {% if vote %}
                    <button type="submit" class="btn btn-danger btn-lg">투표취소 <span class="badge">{{idea.vote_set.count}}</span></button>
                {% else %}
                    <button type="submit" class="btn btn-primary btn-lg">투표하기 <span class="badge">{{idea.vote_set.count}}</span></button>
                {% endif %}
            </form>
            <hr>
        </div>


        <!-- <div class="row col-sm-12">
            <div class="panel panel-default">
                <div class="panel-heading text-center">{{idea.title}}</div>
                <div class="panel-body">
                    <div class="row">
                        <div class="col-sm-12">
                            {{idea.contents}}
                        </div>
                    </div>
                    <hr class="small left" style="margin: 25px auto;">
                    <div class="row">
                        <img src="{{idea.image.url}}" class="img-responsive center-block" width="80%" >
                    </div>
                </div>
                <div class="panel-footer">
                    <div class="row small text-center">
                        작성일시: {{idea.created_at|date:'Y-m-d H:i'}}
                    </div>
                    <div class="row small text-center">
                        마지막 수정일시: {{idea.updated_at|date:'Y-m-d H:i'}}
                    </div>
                    {% if idea.author == user %}
                    <div class="row">
                        <div class="col-xs-3 col-xs-offset-3 text-right">
                            <a class="btn btn-xs btn-primary" href="{% url 'idea:idea_edit' idea.pk %}">수정</a>
                        </div>
                        <div class="col-xs-3">
                            <a class="btn btn-xs btn-danger" href="{% url 'idea:idea_del' idea.pk %}">삭제</a>
                        </div>
                    </div>
                    {% endif %}
                </div>
            </div>
        </div> -->

    {# 댓글 다는 부분 #}
        <div class="row col-sm-9 col-md-offset-1">
            <section class="comment">
                <article class="row">
                    <div class="col-sm-2 hidden-xs">
                        {# 개인 프로필 사진 넣기 #}
                        <figure class="thumbnail user-photo">
                            {% if user.socialaccount_set.all %}
                            {%for account in user.socialaccount_set.all%}
                                {% if account.extra_data.properties.profile_image %}
                                    <img src = {{account.extra_data.properties.profile_image}}>
                                {% else %}
                                    <img src = "https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                                {% endif %}
                            {% endfor %}
                            {% else %}
                                <img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" >
                            {% endif %}
                        </figure>
                    </div>
                    <div class="col-sm-9">
                        <div class="comment-list">
                            <div class="panel panel-default arrow left">
                                <div class="panel-body">
                                    {# <form action="" method="POST" enctype="multipart/form-data"> #}
                                        {% bootstrap_form form layout='inline' %}
                                        <div id="results"></div>
                                        <div style="display:none;" id="comment-footer">
                                            <button class="btn btn-primary btn-xs pull-right add_comment">확인</button>
                                            <span class="pull-right">&nbsp;</span>
                                            <button class="btn btn-danger btn-xs pull-right form-cancel">취소</button>
                                        </div>
                                    {# </form> #}
                                </div>
                            </div>
                        </div>
                    </div>
                </article>
            </section>
            <hr>
        </div>

    {# 댓글 보는 부분 #}
    <div class="row col-sm-9 col-md-offset-1 comment-block">
        {% if comments %}
        <section class="comment-list">
            {% for comment in comments %}
                <article class="row">
                    <div class="col-sm-2 hidden-xs">
                        {# ---프로필 사진이 들어갈 곳--- #}
                        <figure class="thumbnail user-photo">
                            {% if comment.author.socialaccount_set.all %}
                                {%for account in comment.author.socialaccount_set.all%}
                                    {% if account.extra_data.properties.profile_image %}
                                        <img src = {{account.extra_data.properties.profile_image}}>
                                    {% else %}
                                        <img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png">
                                    {%endif%}
                                {% endfor %}
                            {% else %}
                                <img src="https://ssl.gstatic.com/accounts/ui/avatar_2x.png" >
                            {%endif%}
                        </figure>
                    </div>
                    <div class="col-sm-9">
                        <div class="panel panel-default arrow left">
                            <div class="panel-body no-padding">
                                <header class="text-left">
                                    <div class="comment-user">
                                    {%if comment.author == user %}
                                    <div class="dropdown btn-group pull-right">
                                        <i class="fa fa-bars" aria-hidden="true" data-toggle="dropdown"></i>
                                        <ul class="dropdown-menu" style="min-width: 30px">
                                        <li><a href="javascript:void(0)" class="a_comment_edit">수정</a></li>
                                        <li><a href="{% url 'idea:comment_del' idea.pk comment.pk %}">삭제</a></li>
                                        </ul>
                                    </div>
                                    {% endif %}
                                    <i class="fa fa-user"></i>
                                        <strong>
                                        {% if comment.author.socialaccount_set.all %}
                                            {%for account in comment.author.socialaccount_set.all%}
                                                {% if account.provider == "facebook" %}
                                                    {{comment.author.last_name}}{{comment.author.first_name}}
                                                {% elif account.provider == "kakao" %}
                                                    {{comment.author.first_name}}
                                                {%endif%}
                                            {% endfor %}
                                        {% else %}
                                            {{comment.author}}
                                        {% endif %}
                                        </strong>
                                    </div>
                                    <time class="comment-date small text-muted">
                                        <i class="fa fa-clock-o"></i>
                                        {{comment.elapsed_time}}
                                        {% if comment.created_at|date:'YmdHms' != comment.updated_at|date:'YmdHms' %}
                                        (수정됨)
                                        {% endif %}
                                    </time>
                                </header>
                                {# <form action="" method="POST" enctype="multipart/form-data"> #}
                                    <input type="hidden" class="comment-pk" value="{{comment.pk}}">
                                    <div class="comment-post">
                                        <span class="comment-content">{{comment.contents}}</span>
                                    </div>
                                    <div class="comment-post-buttons" style="display:none">
                                        <button class="btn btn-primary btn-xs edit-submit">확인</button> <button class="btn btn-danger btn-xs edit-cancel">취소</button>
                                    </div>
                                {# </form> #}
                            </div>
                        </div>
                    </div>
                </article>
            {% endfor %}
        </section>
            {% else %}
                <div class="row col-xs-12">
                    댓글없음
                </div>
        {% endif %}
        </div>
    </div>

{% endblock %}

{% block script %}
    <script>
        function edit(){
            return "{% static 'js/comment_edit.js' %}"
        }

        $(document).ready(function (){
            $('.page-heading.idea').on('click', function (){
                location.href = '/idea/'
            })
            $('#edit').on('click', function (){
                location.href = "{% url 'idea:idea_edit' idea.pk %}"
            })
            $('#delete').on('click', function (){
                if (confirm('삭제하시겠습니까?'))
                    location.href = "{% url 'idea:idea_del' idea.pk %}"
            })
        })
    </script>
    <script src="{% static 'js/comment_edit.js' %}"></script>
    <script src="{% static 'js/comment_add.js' %}"></script>

{% endblock %}

idea/templates/idea/idea_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load thumbnail %}
{% block content %}
<!-- Page Header -->
<!-- Set your background image for this header on the line below. -->
<header class="intro-header" style="background-image: url('{% static 'img/idea.jpg' %}')">
    <div class="container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                <div class="page-heading idea">
                    <h1>Idea</h1>
                    <hr class="small">
                    <span class="subheading">This is what We do.</span>
                </div>
            </div>
        </div>
    </div>
</header>
<!-- Main Content -->
<div class="container-fluid">

        <div class="col-md-offset-1 col-md-10 col-sm-12">
            {%if user.is_authenticated %}
            <div class="text-right">
                <a href="{% url 'idea:idea_new' %}"><h4>[새 글쓰기]</h4></a>
            </div>
            {% endif %}

            <div class="show-like-table col-sm-12">
            {% for idea in idea_list %}
            <div class="col-md-4 col-sm-6 col-xs-12 wow slideInUp" data-wow-delay="0.1s">
                <a href="{% url 'idea:idea_detail' idea.pk %}">
                    <div class="idea_container">
                        <div class="img_container container-fluid">
                            {% if idea.image %}
                                {% thumbnail idea.image "150x100" crop="center" as im %}
                                <img src="{{im.url}}" width="{{im.width}}" height="{{im.height}}" class="img-responsive col-xs-12" alt="">
                                {% endthumbnail %}
                            {% else %}
                            <h3>{{idea.title}}</h3>
                            {% endif %}
                        </div>
                        <div class="idea_title">
                            <h3>{{idea.title}}</h3>
                            <div class="wrap"><i class="fa fa-user" aria-hidden="true"></i> {{idea.author.resume.name}}&nbsp득표수:{{idea.vote_set.count}}</div>
                            <div class="span12"><i class="fa fa-clock-o" aria-hidden="true"></i> {{idea.updated_at|date:'Y-m-d H:m'}}</div>
                        </div>
                    </div>
                </a>
            </div>
            {% endfor %}
            </div>
            <!-- Pager
             <ul class="pager">
                 <li class="next">
                     <a href="#">Older Posts &rarr;</a>
                 </li>
             </ul>
             -->
        </div>
    </div>

{% endblock %}
{% block script %}
<script>
    new WOW().init();
    $(document).ready(function (){
        $('.page-heading.idea').on('click', function (){
            location.href='/idea/'
        })
    })
</script>
{% endblock %}